name: Tests
on: 
  workflow_dispatch: {}
  push:
    paths: ['src/**', 'tests/**']

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        poetry-version: ["1.3.1"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
     
      - name: Install
        run: poetry install --with test,dev

      - name: Lint
        run: poetry run black --line-length 100 src tests --exclude src/kafkactl/cli.py --check
      
      - name: Tests
        run: |
          poetry run coverage run -m unittest discover tests -v
          poetry run coverage lcov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
